### ISSUE TITLE
reverse proxy

### ISSUE THREAD

**Issue by qiangweihewu** [DIBgram/DIBgram#8]
Thanks for making such a wonderful app! I wonder whether it is possible to host it on my own server with reverse proxy so that those regions that telegram is blocked could use it freely.

**Comment by Mammad900** [comment]
Hi @qiangweihewu,
It is not possible to circumvent blockages by hosting DIBgram with a reverse proxy, because that would only work for app resources which are not regionally blocked. DIBgram will still connect to the Telegram servers directly and will not use that reverse proxy.

A potential solution is to use a separate WebSocket server that forwards the connection to the Telegram servers, but unfortunately it is not possible to make TDLib connect to that server instead of Telegram servers. 

The only way to connect to Telegram in regions where it is blocked is to set a system proxy or use a VPN.
